# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7

        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          # MYSQL_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_DATABASE: squalor_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Check MySQL
      run: |
        mysql -h=mysql -u=root -p=root -e 'CREATE DATABASE squalor_test;'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        export MYSQL_PASSWORD='root'
        export MYSQL_HOSTNAME='mysql'
        go test -v -race ./...
